---
- name: Restart openvpn
  become: yes
  service:
    name: "openvpn-server@{{ role_name | replace('-', '_') }}.service"
    state: restarted

- name: Restart dnsmasq
  become: yes
  service:
    name: dnsmasq
    state: restarted

- name: Restart dhcpcd
  become: yes
  service:
    name: dhcpcd
    state: restarted

- name: Restart hostapd
  become: yes
  service:
    name: hostapd
    state: restarted
